%%
%% Autogenerated by Thrift Compiler (0.10.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(scribe_types).

-include("scribe_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('LogEntry') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('LogEntry') ->
  {struct, [{1, undefined, string, 'category', undefined},
          {2, undefined, string, 'message', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['LogEntry'].

enum_info('ResultCode') ->
  [
    {'OK', 0},
    {'TRY_LATER', 1}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['ResultCode'].

exception_names() ->
  [].

