%%
%% Autogenerated by Thrift Compiler (0.10.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(scribe_thrift).
-behaviour(thrift_service).


-include("scribe_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% Log(This, Messages)
function_info('Log', params_type) ->
  {struct, [{1, {list, {struct, {'scribe_types', 'LogEntry'}}}}]}
;
function_info('Log', reply_type) ->
  i32;
function_info('Log', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['Log'].

