%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(zipkin_core_types).

-include("zipkin_core_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Endpoint') ->
  {struct, [{1, i32},
          {2, i16},
          {3, string},
          {4, string}]}
;

struct_info('Annotation') ->
  {struct, [{1, i64},
          {2, string},
          {3, {struct, {'zipkin_core_types', 'Endpoint'}}}]}
;

struct_info('BinaryAnnotation') ->
  {struct, [{1, string},
          {2, string},
          {3, i32},
          {4, {struct, {'zipkin_core_types', 'Endpoint'}}}]}
;

struct_info('Span') ->
  {struct, [{1, i64},
          {3, string},
          {4, i64},
          {5, i64},
          {6, {list, {struct, {'zipkin_core_types', 'Annotation'}}}},
          {8, {list, {struct, {'zipkin_core_types', 'BinaryAnnotation'}}}},
          {9, bool},
          {10, i64},
          {11, i64},
          {12, i64}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Endpoint') ->
  {struct, [{1, undefined, i32, 'ipv4', undefined},
          {2, undefined, i16, 'port', undefined},
          {3, undefined, string, 'service_name', undefined},
          {4, optional, string, 'ipv6', undefined}]}
;

struct_info_ext('Annotation') ->
  {struct, [{1, undefined, i64, 'timestamp', undefined},
          {2, undefined, string, 'value', undefined},
          {3, optional, {struct, {'zipkin_core_types', 'Endpoint'}}, 'host', #'Endpoint'{}}]}
;

struct_info_ext('BinaryAnnotation') ->
  {struct, [{1, undefined, string, 'key', undefined},
          {2, undefined, string, 'value', undefined},
          {3, undefined, i32, 'annotation_type', undefined},
          {4, optional, {struct, {'zipkin_core_types', 'Endpoint'}}, 'host', #'Endpoint'{}}]}
;

struct_info_ext('Span') ->
  {struct, [{1, undefined, i64, 'trace_id', undefined},
          {3, undefined, string, 'name', undefined},
          {4, undefined, i64, 'id', undefined},
          {5, optional, i64, 'parent_id', undefined},
          {6, undefined, {list, {struct, {'zipkin_core_types', 'Annotation'}}}, 'annotations', []},
          {8, undefined, {list, {struct, {'zipkin_core_types', 'BinaryAnnotation'}}}, 'binary_annotations', []},
          {9, optional, bool, 'debug', false},
          {10, optional, i64, 'timestamp', undefined},
          {11, optional, i64, 'duration', undefined},
          {12, optional, i64, 'trace_id_high', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

