%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(zipkin_dependencies_types).

-include("zipkin_dependencies_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('DependencyLink') ->
  {struct, [{1, string},
          {2, string},
          {4, i64}]}
;

struct_info('Dependencies') ->
  {struct, [{1, i64},
          {2, i64},
          {3, {list, {struct, {'zipkin_dependencies_types', 'DependencyLink'}}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('DependencyLink') ->
  {struct, [{1, undefined, string, 'parent', undefined},
          {2, undefined, string, 'child', undefined},
          {4, undefined, i64, 'callCount', undefined}]}
;

struct_info_ext('Dependencies') ->
  {struct, [{1, undefined, i64, 'start_ts', undefined},
          {2, undefined, i64, 'end_ts', undefined},
          {3, undefined, {list, {struct, {'zipkin_dependencies_types', 'DependencyLink'}}}, 'links', []}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

