%%
%% Autogenerated by Thrift Compiler (0.10.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("zipkin_core_types.hrl").

-define(ZIPKIN_CORE_CLIENT_SEND, "cs").

-define(ZIPKIN_CORE_CLIENT_RECV, "cr").

-define(ZIPKIN_CORE_SERVER_SEND, "ss").

-define(ZIPKIN_CORE_SERVER_RECV, "sr").

-define(ZIPKIN_CORE_WIRE_SEND, "ws").

-define(ZIPKIN_CORE_WIRE_RECV, "wr").

-define(ZIPKIN_CORE_CLIENT_SEND_FRAGMENT, "csf").

-define(ZIPKIN_CORE_CLIENT_RECV_FRAGMENT, "crf").

-define(ZIPKIN_CORE_SERVER_SEND_FRAGMENT, "ssf").

-define(ZIPKIN_CORE_SERVER_RECV_FRAGMENT, "srf").

-define(ZIPKIN_CORE_HTTP_HOST, "http.host").

-define(ZIPKIN_CORE_HTTP_METHOD, "http.method").

-define(ZIPKIN_CORE_HTTP_PATH, "http.path").

-define(ZIPKIN_CORE_HTTP_URL, "http.url").

-define(ZIPKIN_CORE_HTTP_STATUS_CODE, "http.status_code").

-define(ZIPKIN_CORE_HTTP_REQUEST_SIZE, "http.request.size").

-define(ZIPKIN_CORE_HTTP_RESPONSE_SIZE, "http.response.size").

-define(ZIPKIN_CORE_LOCAL_COMPONENT, "lc").

-define(ZIPKIN_CORE_ERROR, "error").

-define(ZIPKIN_CORE_CLIENT_ADDR, "ca").

-define(ZIPKIN_CORE_SERVER_ADDR, "sa").

